name: Metrics
on:
  schedule:
    - cron: "0 0 * * *" # Daily at midnight
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: mohiuddin-khan-shiam
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Dhaka
          config_display: columns
          config_padding: 0, 6
          config_output: auto
          
          # Compact plugins
          plugin_lines: yes
          plugin_languages: yes
          plugin_languages_limit: 6
          plugin_languages_threshold: 2%
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
