name: Metrics
on:
  schedule:
    - cron: "0 0 * * *" # Daily at midnight
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Header Section
      - name: Header metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/header.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: mohiuddin-khan-shiam
          template: classic
          base: header
          config_timezone: Asia/Dhaka
          
      # Activity Section  
      - name: Activity metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: mohiuddin-khan-shiam
          template: classic
          base: activity, community
          config_timezone: Asia/Dhaka
          
      # Repository Section
      - name: Repository metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/repositories.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: mohiuddin-khan-shiam
          template: classic
          base: repositories, metadata
          config_timezone: Asia/Dhaka
          
      # Languages Section
      - name: Languages metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: mohiuddin-khan-shiam
          template: classic
          base: ""
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          config_timezone: Asia/Dhaka
          
      # Lines of Code Section
      - name: Lines metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/lines.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: mohiuddin-khan-shiam
          template: classic
          base: ""
          plugin_lines: yes
          plugin_followup: yes
          plugin_stargazers: yes
          config_timezone: Asia/Dhaka
          
      # Calendar Section
      - name: Calendar metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/calendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: mohiuddin-khan-shiam
          template: classic
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          config_timezone: Asia/Dhaka
