name: Generate Snake Game

# Controls when the action will run
on:
  schedule:
    # Runs every 12 hours
    - cron: "0 */12 * * *"
  
  # Allows you to run this workflow manually
  workflow_dispatch:
  
  # Run on every push to main
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: mohiuddin-khan-shiam
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark&color_snake=#7c3aed&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
